services:
  db:
    image: postgres:15-alpine
    container_name: nairatrack-db
    environment:
      POSTGRES_DB: nairatrack
      POSTGRES_USER: nairatrack
      POSTGRES_PASSWORD: nairatrack
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U nairatrack" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - nairatrack-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nairatrack-api
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.dev
      - DB_HOST=db
      - DB_NAME=nairatrack
      - DB_USER=nairatrack
      - DB_PASSWORD=nairatrack
      - SECRET_KEY=dev-secret-key-change-in-production
      - AUTH0_DOMAIN=dev-54nxe440ro81hlb6.us.auth0.com
      - AUTH0_API_AUDIENCE=https://personal-finance-api.namelesscompany.cc
      - CORS_ALLOWED_ORIGINS=http://localhost:3000
      - DEV_AUTH_BYPASS=false
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app
    command: >
      sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    networks:
      - nairatrack-network

  frontend:
    build:
      context: ../personal-finance-fe
      dockerfile: Dockerfile
    container_name: nairatrack-frontend
    ports:
      - "3000:3000"
    environment:
      # Client-side Auth0 variables (Required for @auth0/auth0-react)
      - NEXT_PUBLIC_AUTH0_DOMAIN=dev-54nxe440ro81hlb6.us.auth0.com
      - NEXT_PUBLIC_AUTH0_CLIENT_ID=SM3sFfXc1ntYVIeWY1g16pVnuSsYUI7k
      - NEXT_PUBLIC_AUTH0_AUDIENCE=https://personal-finance-api.namelesscompany.cc
      - NEXT_PUBLIC_AUTH0_REDIRECT_URI=http://localhost:3000
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:8000/api/v1
    depends_on:
      - api
    networks:
      - nairatrack-network

volumes:
  postgres_data:


networks:
  nairatrack-network:
    name: nairatrack-network
    driver: bridge
